### ISSUE TITLE
Undeclared dependency on rimraf

### ISSUE THREAD

**Issue by wojtekmaj** [isaacs/sock-daemon#4]
Hi,
I tried to use sock-daemon (via tsimp) in my server project. When trying to start Node with tsimp as a loader, I was immediately hit with an error:

```
server % yarn dev

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
file:///server/node_modules/sock-daemon/dist/esm/starting-lock.js:7
import { rimraf } from 'rimraf';
         ^^^^^^
SyntaxError: Named export 'rimraf' not found. The requested module 'rimraf' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'rimraf';
const { rimraf } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async Hooks.register (node:internal/modules/esm/hooks:139:26)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:168:18)

Node.js v20.9.0
```

Upon investigation, it turns out sock-daemon does not declare rimraf as its dependency and, as a result:

* In node_modules, uses whatever it finds (and in my case, it was rimraf@3, not rimraf@5)
* In PnP, doesn't work at all

To further test my diagnosis, I have used Yarn's packageExtensions that allows you to patch misconfigured dependencies:

```
packageExtensions:
  "sock-daemon@*":
    dependencies:
      rimraf: ^5.0.5
```

And poof! The error was gone, proving that this was the issue.

**Comment by isaacs** [comment]
https://github.com/isaacs/sock-daemon/commit/f56530a252f67ae21c6784b61dd8e5246e972b8d
