### ISSUE TITLE
Replace `rimraf` with `fs.rmSync(path, { recursive: true })`

### ISSUE THREAD

**Issue by wojtekmaj** [isaacs/sock-daemon#6]
`sock-daemon` works with Node.js v16.17.0 and up, according to `package.json` `engines` entry.

In Node.js v14.14.0, [`fs.rmSync`](https://nodejs.org/api/fs.html#fsrmsyncpath-options) was added. It's a built-in module that removes files and directories. The `recursive` option is used to remove directories and their contents.

Given the above, I believe you could safely replace `rimraf` with `fs.rmSync(path, { recursive: true })` and reduce the number of dependencies in this project.

**Comment by isaacs** [comment]
It's less reliable on Windows.

**Comment by wojtekmaj** [comment]
I see! Thanks for explanation :)
